login page responsive
chingu-voyages/v8-chimeras-team-04 pull request #31
Opened 2019-04-29 21:37 UTC by paul1124

2019-04-30 04:03 UTC, terrancexin commented on client/src/Components/AppStage/AppStage.scss
> +  }
try to avoid `!important` by any means...

2019-04-30 04:09 UTC, terrancexin requested changes
is there an alternative approach than using `!important`?

2019-04-30 05:11 UTC, clockwerkz approved these changes
I left a minor note on elements breaking out when resized horizontally, but I don't think it should hold back from submission. At this point we gotta get moving.

2019-05-01 01:33 UTC, nroode reviewed
For the mobile Login view, let's remove the green 'margin' along the sides and bottom of the app.  Let's also reduce the padding a bit around the title and center the title.

I think it also might be good to adjust the colors a bit so the Login is not so distinctly placed/defined but instead blends into the background more.

2019-05-01 06:17 UTC, closed without merging