login field
chingu-voyages/v8-chimeras-team-04 pull request #6
Opened 2019-03-20 22:01 UTC by paul1124

renamed branch fe_login to feature/login

2019-03-21 01:38 UTC, clockwerkz commented
Looks good, Paul :)

2019-03-22 04:53 UTC, terrancexin requested changes
let's use React Hooks for Login.jsx

2019-03-24 18:26 UTC, paul1124 commented
> why do you need both setPw and setPassword?

Since I need to submit both username and password when I'm trying to bypass the login page. The setPw works just like value, where I'm trying to only handleChange for the password input. I can't do use [value, setValue] for both username and password, because handleSubmit is going to take account of both username and password, and setValue is going to change username only via handleChange.

2019-03-24 19:08 UTC, terrancexin commented
```js
import React, { useState } from 'react';

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div className="login">
      <form onSubmit={handleSubmit}>
        <label>Username: </label>
        <input
          type="text"
          value={username}
          onChange={e => setUsername(e.target.value)}
        />
        <label>Password: </label>
        <input
          type="password"
          value={password}
          onChange={e => setPassword(e.target.value)}
        />
        <button onClick={handleSubmit}>Log In</button>
      </form>
    </div>
  )

  function handleSubmit(e) {
    e.preventDefault();
  
   // Good job with UI validation before we're sending back the data to the UI, we should connect further to chat about different approaches for error validations. It's very interesting to think about.
    if (username.length < 4 && password.length < 4) return;

  // and in this submit function you can make a HTTP POST request to send the user data back to our backend server
    axios.post('/auth', { username, password })
      .then(data => console.log(data))
  }
}
```

let me know if you have any questions on the code or comment.

2019-03-24 23:11 UTC, nroode reviewed
looks good Paul - though the imports weren't working for me since they referenced the 'Components' folder (upper case) instead of 'components'

2019-03-25 16:17 UTC, clockwerkz requested changes
Looking good, Paul!
Yeah the only thing is you have "Components" vs "components" I think we had "components" already, but let's choose one folder and use that moving forward. :)

2019-03-25 17:53 UTC, terrancexin commented
👍

2019-03-25 17:53 UTC, terrancexin approved these changes

2019-03-25 17:53 UTC, terrancexin commented on client/src/Components/Login.jsx
> +      <LoginForm setUsername={setUsername} setPassword={setPassword} />
why are you passing in setState functions?

2019-03-25 17:53 UTC, terrancexin commented on client/src/Components/Login.jsx
> +function LoginForm({ setUsername, setPassword }) {
you should merge these into one component, the setPassword and setPw are reusable.

2019-03-25 17:58 UTC, merged